ENH Prefer dependency injection for GridFieldComponents
silverstripe/silverstripe-reports pull request #147
Opened 2022-02-12 05:37 UTC by GuySartorelli

GridFieldComponents packaged with silverstripe/framework are injectable as of 4.11.0 (see silverstripe/silverstripe-framework#10204)
Explicitly invoking the injector here instead of using `create()` allows backwards compatability with framework < 4.11.0 while ensuring dependency injection is still used from 4.11.0 onwards.
See silverstripe/silverstripe-admin#1286 for (brief) discussion of this approach vs using `::create()`.

2022-02-12 05:54 UTC, GuySartorelli commented
Travis build errors because there is no `4.11` branch/tag for silverstripe/framework currently.

2022-03-03 03:10 UTC, emteknetnz requested changes
Require framework `^4.11` and use the `::create()` syntax instead please

2022-03-03 04:48 UTC, emteknetnz commented
You'll need to rebase

2022-03-03 04:48 UTC, GuySartorelli commented
@emteknetnz Done!

2022-03-03 04:50 UTC, emteknetnz commented
You'll need to rebase @GuySartorelli

2022-03-03 04:52 UTC, GuySartorelli commented
@emteknetnz Oops, good note. Rebased on 4.

2022-03-03 21:13 UTC, emteknetnz approved these changes

2022-03-03 21:13 UTC, merged