NEW Migrate code from other modules
silverstripe/silverstripe-reports pull request #204
Opened 2024-11-20 00:08 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/884

Separate commits so please do no squash merge

2024-11-26 21:16 UTC, GuySartorelli requested changes
The external broken links report doesn't work. I click "create new report" and it does nothing. Looking at the dev console there are some missing files. I think you're missing the `expose` entry for `client/dist` in `composer.json`

The folder structure between the newly copied code is also not standardised. e.g. `ExternalLinks` has a `Reports` subfolder, but the other two don't. Please make the folder structure uniform across all three feature dirs.

2024-11-26 21:16 UTC, GuySartorelli commented on tests/behat/src/FeatureContext.php
Need composer autoload entry for `tests/behat/src`

2024-11-26 21:16 UTC, GuySartorelli commented on client/src/styles/sitewidecontentreport.scss
If we're having stuff in `client/src` and `client/dist` then the `javacscript` dir should be included and built out at the same time.

It's fair if you want to say that's out of scope (though ideally it'd be done at the same time as we update the folder structure, and will take very little time to do) - in that case it needs to have a follow-up card.

2024-11-26 21:16 UTC, GuySartorelli commented on README.md
> +## External broken links report
These should Moved to the main docs, or else this module's docs should be exposed in the "Optional features" section.

Given reports are part of installer, probably the former.

2024-11-27 00:58 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
That's already in the PR?

2024-11-27 01:05 UTC, GuySartorelli commented on tests/behat/src/FeatureContext.php
So it is 😅

2024-11-27 01:49 UTC, emteknetnz commented on client/src/styles/sitewidecontentreport.scss
Done

2024-11-27 01:59 UTC, emteknetnz commented on README.md
> +## External broken links report
The problem there is we'd basically need to a new reports section. Currently the only reports thing there is https://docs.silverstripe.org/en/5/developer_guides/customising_the_admin_interface/how_tos/customise_site_reports/ which doesn't seem like an appropriate place to dump in info about the external links report etc

We're currently just moving docs from one readme to another, I think at least for the scope of what we're doing this is acceptable

2024-11-27 02:11 UTC, emteknetnz commented
> The external broken links report doesn't work. I click "create new report" and it does nothing. Looking at the dev console there are some missing files. I think you're missing the expose entry for client/dist in composer.json

Works fine on my local

> The folder structure between the newly copied code is also not standardised. e.g. ExternalLinks has a Reports subfolder, but the other two don't. Please make the folder structure uniform across all three feature dirs.

Have updated

2024-11-27 21:05 UTC, GuySartorelli commented
External broken links report still doesn't work for me. I'm just using installer (not sink) and pulling in only this PR since it shouldn't rely on any of the other changes from what I can tell.

2024-11-27 21:12 UTC, GuySartorelli requested changes

2024-11-27 21:12 UTC, GuySartorelli commented on code/SiteWideContentReport/Model/SitewideContentTaxonomy.php
> +namespace SilverStripe\Reports\SiteWideContentReport\Model;
```suggestion
namespace SilverStripe\Reports\SiteWideContentReport\Extensions;
```
And rename the `Model` dir to `Extensions`

2024-11-27 21:12 UTC, GuySartorelli commented on README.md
> +## External broken links report
I really don't think documentation belongs in a readme. At the very least move it into a `docs/` dir in here.

2024-11-27 22:19 UTC, emteknetnz commented on code/SiteWideContentReport/Model/SitewideContentTaxonomy.php
> +namespace SilverStripe\Reports\SiteWideContentReport\Model;
Done

2024-11-27 22:25 UTC, emteknetnz commented
Have moved docs for external links + site wide content report do docs/en/index.md

2024-11-28 01:31 UTC, GuySartorelli approved these changes
LGTM

2024-11-28 01:31 UTC, merged